# -*- coding: utf-8 -*-
"""Copy of Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o7Xyhg-QyNRdz0nOQ0nypDlx9KxJpKn3
"""

##list

vivek=["johny","sunny","bunny","funny"]
print(vivek)

a="puppy"
print(a)
print(type(a))
print(a[1])

a="puppy"
print(a)
print(len(a))

a="cat dog"
print(len(a))

a="rrr movie released"
print("rrr" in a)

a="rrr movie released"
print("h" not in a)

a="rrr movie released"
print("h" in a)

##slicing

a="rrr movie released"
print(a[2:5])